CREATE TABLE transactions_pin (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    pin VARCHAR(50) NOT NULL,
    attempt INT NOT NULL,
    blocked BOOLEAN NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME
);
