spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ CleanArchitecture
    username: root
    password: ${MYSQL_PASSWORD}
    baseline-on-migrate: true
    driverClassName: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
security:
  jwt:
    secret: 0412c946-a382-4be6-9245-ebde9ef911dd
    expiration: 900
